name: Python Test Workflow

on:
  push:
    paths:
      - "Leetcode/**"
  pull_request:
    paths:
      - "Leetcode/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10.9

      - name: Upgrade pip and Install Pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
